# ==============================================================================
# Script: 05.2_RF_optimization_summary.R
# Project: Farm Size Prediction Across Sub-Saharan Africa
# Purpose: Summarize RF optimization results
#
# Authors: Deo, Joao, Robert, Fred
# Code documentation: Claude (Anthropic) - February 2026
# ==============================================================================


ff <- list.files("output/RFoptim", pattern="\\.Rds$", full=TRUE)
res <- lapply(ff, \(f) readRDS(f)$results)

res <- data.frame(filename=basename(ff), do.call(rbind, res))
res <- res[order(-res$Rsquared, res$RMSE, res$MAE), ]
saveRDS(res, "output/tables/RF_optim_summarized_table.rds")


# # Compile results of RF optimization
# 
# # load packages
# require(tidyverse)
# require(httr)
# require(rvest)
# 
# #-------------------------------------------------
# # Results were generated by 100 super-computers (thanks to Robert), and stored at 'https://geodata.ucdavis.edu/fsa/RFoptim'
# 
# # --------------------------------------------------
# # List of model outputs (.rds files)
# rf_models <- rvest::read_html('https://geodata.ucdavis.edu/fsa/RFoptim') |>
#   rvest::html_nodes('a') |>
#   rvest::html_attr('href')
# model_output <- rf_models[grepl('\\.rds$', rf_models, ignore.case = T)]
# 
# # Function to extract the result table from any valid model output
# summarize_rfoptim <- function(filename){
#   url <- paste0('https://geodata.ucdavis.edu/fsa/RFoptim/', filename)
#   temp_file <- tempfile(fileext = ".rds")
#   deb <- Sys.time()
#   tryCatch(
#     httr::GET(url, httr::write_disk(temp_file, overwrite = T)),
#     error = function(e) cat('there was a glitch'),
#     finally = print(' ')
#   )
#   out <- readRDS(temp_file)
#   one_row <- cbind(filename = filename, out$results)
#   fin <- Sys.time() - deb
#   print(paste0('------ ', filename,  ' downloaded ----------'))
#   print(fin)
#   return(one_row)
# }
# 
# # Table of all results
# all_rf_result_table <- do.call(rbind, lapply(model_output, summarize_rfoptim))
# all_rf_result_table <- all_rf_result_table |>
#   arrange(-Rsquared, RMSE, MAE)
# saveRDS(all_rf_result_table, '../output/tables/RF_optim_summarized_table.rds')
# write.csv(all_rf_result_table, file = '../output/tables/RF_optim_summarized_table.csv', row.names = F)
# 
# # ------------------------------------------------------------------------------
# # Send an email 
# from <- 'test@noreply.com'
# to <- 'd.hougni@cgiar.org'
# username = 'curlpackage'
# password  = 'qyyjddvphjsrbnlm'
# subject <- 'Task Completed'
# body <- 'From: "CGLabs Terminal" <test@noreply.com>
# To: "Deo" <d.hougni@cgiar.org>
# Subject: task successfully completed!
# 
# The task has been successfully completed. Check the output folder on CGLabs.'
# 
# curl::send_mail(
#   from, to, 
#   body, 
#   smtp_server = 'smtps://smtp.gmail.com',
#   username = username, 
#   password  = password
# )
