# ==============================================================================
# Script: F01_main_figure1.R
# Project: Farm Size Prediction Across Sub-Saharan Africa
# Purpose: Main Figure 1 — 4 panels:
#          A) Farm density map (farms per 100 km²)
#          B) Predicted median farm size map
#          C) Predicted vs census nb farms (Lowder comparison, log scale)
#          D) Reported vs OOB-predicted farm size (2D density)
#
# PRODUCTION inputs (all one level above scripts/):
#   ../fig.1a_nb_of_farm_per_grid_cell.tif  — 2-layer raster: spam_2017, pred_farm_area_ha
#   ../fig.1c_comparison_with_sarah_lowder.rds — list: comp_nb_farms, r2_sarah
#   ../fig.1d_reported_vs_predicted_fsize.rds  — list: lsms_spatial (farm_area_ha, pred_oob)
#
# CI: stubs generated by 00.3_synthetic_data.R saved to ../data/processed/fig1_*.
#     Path patched below via tryCatch fallback.
# Output: ../output/main_fig/Fig.01.png
# ==============================================================================

source("00_report_utils.R")
t0 <- proc.time()[["elapsed"]]
require(tidyverse)
require(MASS)
setwd(paste0(here::here(), "/scripts"))
dir.create("../output/main_fig", recursive = TRUE, showWarnings = FALSE)

# ── SSA boundary ──────────────────────────────────────────────────────────────
input_path <- "../data/raw/spatial"
country    <- geodata::world(path = input_path, resolution = 5, level = 0)
isocodes   <- geodata::country_codes()
if (!"UNREGION1" %in% names(isocodes)) {
  ssa_i3 <- c("AGO","CMR","CAF","TCD","COD","COG","GAB","GNQ","STP",
               "BWA","LSO","MWI","MOZ","NAM","ZAF","SWZ","ZMB","ZWE",
               "BDI","COM","DJI","ERI","ETH","KEN","MDG","MUS","RWA","SDN","SSD","SOM","TZA","UGA",
               "BEN","BFA","CPV","CIV","GMB","GHA","GIN","GNB","LBR","MLI","MRT","NER","NGA",
               "SEN","SLE","TGO","SDN")
  isocodes_ssa <- subset(isocodes, ISO3 %in% ssa_i3)
} else {
  isocodes_ssa <- subset(isocodes,
    NAME == "Sudan" |
    UNREGION1 %in% c("Middle Africa","Western Africa","Southern Africa","Eastern Africa"))
  isocodes_ssa <- subset(isocodes_ssa,
    !NAME %in% c("Cabo Verde","Comoros","Mauritius","Mayotte","Réunion",
                 "Saint Helena","São Tomé and Príncipe","Seychelles"))
}
ssa <- subset(country, country$GID_0 %in% isocodes_ssa$ISO3)

# ── Palettes ──────────────────────────────────────────────────────────────────
pal4 <- colorRampPalette(c("#A1D99B","#00441B"))

# ── Load inputs (production paths; CI fallback to data/processed stubs) ───────
fig1a <- tryCatch(
  terra::rast("../fig.1a_nb_of_farm_per_grid_cell.tif"),
  error = function(e) terra::rast("../data/processed/fig1a_stub.tif"))

fig1c <- tryCatch(
  readRDS("../fig.1c_comparison_with_sarah_lowder.rds"),
  error = function(e) readRDS("../data/processed/fig1c_stub.rds"))

fig1d <- tryCatch(
  readRDS("../fig.1d_reported_vs_predicted_fsize.rds"),
  error = function(e) readRDS("../data/processed/fig1d_stub.rds"))

# ── Rwanda nb_farms correction (from original) ────────────────────────────────
fig1c$comp_nb_farms$nb_farms[fig1c$comp_nb_farms$country == "Rwanda"] <- 1674687
fig1c$r2_sarah <- unname(round(
  cor(na.omit(bind_cols(fig1c$comp_nb_farms$estim_nb_farms,
                        fig1c$comp_nb_farms$nb_farms)))[2, 1]^2, 2))
fig1c$comp_nb_farms$year_class <- cut(
  fig1c$comp_nb_farms$census_year,
  breaks = c(-Inf, 1980, 1990, 2000, 2010, Inf),
  labels = c("1970s","1980s","1990s","2000s","2010s"), right = FALSE)

fig1d_df <- na.omit(data.frame(x = fig1d$lsms_spatial$farm_area_ha,
                                y = fig1d$lsms_spatial$pred_oob))

# ── Plot ───────────────────────────────────────────────────────────────────────
png("../output/main_fig/Fig.01.png", width = 9, height = 8.8, units = "in", res = 200)
par(mfrow = c(2, 2), mar = c(3, 3.5, 1, 1), xaxs = "i", yaxs = "i")

# Panel A: farm density
pal <- pal4
terra::plot(ssa, mar = c(3,3.5,1,1), clip = FALSE, col = "white", main = "",
            panel.first = grid(col = "gray", lty = "solid"), pax = list(cex.axis = 1.8))
terra::plot(fig1a$spam_2017 / fig1a$pred_farm_area_ha,
            breaks = c(0,500,1000,2000,5000,10000,Inf), col = pal(6),
            legend = FALSE, axes = FALSE, add = TRUE)
legend(-16, -5, bty = "y", bg = "white", cex = 1.1, ncol = 1, box.col = "white",
       title = expression("Farms per 100" ~ km^2),
       legend = c("< 500","501 - 1000","1001 - 2000","2001 - 5000","5001 - 10000","> 10000"),
       fill = pal(6), horiz = FALSE)
terra::plot(ssa, axes = FALSE, add = TRUE)
text(48, 26, "A)", cex = 1.5)

# Panel B: predicted farm size
pal <- colorRampPalette(c("#8B0000","#FFCB00","forestgreen"))
terra::plot(ssa, mar = c(3,3.5,1,1), clip = FALSE, col = "white", main = "",
            panel.first = grid(col = "gray", lty = "solid"), pax = list(cex.axis = 1.8))
terra::plot(fig1a$pred_farm_area_ha,
            breaks = c(0,0.5,1,2,5,Inf), col = pal(6),
            legend = FALSE, axes = FALSE, add = TRUE)
legend(-15, -5, bty = "y", bg = "white", cex = 1.1, ncol = 1, box.col = "white",
       title = "Farm size",
       legend = c("< 0.5 ha","0.5 - 1 ha","1 - 1.5 ha","1.5 - 2 ha","2 - 5 ha","> 5 ha"),
       fill = pal(6), horiz = FALSE)
terra::plot(ssa, axes = FALSE, add = TRUE)
text(48, 26, "B)", cex = 1.5)

# Panel C: Lowder scatter (log scale)
plot(log10(fig1c$comp_nb_farms$nb_farms / 1e6),
     log10(fig1c$comp_nb_farms$estim_nb_farms / 1e6),
     xlim = c(-2.5, 1.7), ylim = c(-2.5, 1.7), col = "white",
     cex.axis = 1.2, cex.lab = 1.35, las = 0, mgp = c(2, 0.75, 0),
     xlab = expression(paste("Millions of farms based on census (log"[10]," scale)")),
     ylab = expression(paste("Millions of farms based on predictions (log"[10]," scale)")))
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "whitesmoke")
grid(nx = 8, ny = 8, col = "lightgrey")
abline(a = 0, b = 1)
colr <- viridis::viridis(5, alpha = 0.7)
for (i in seq_along(levels(fig1c$comp_nb_farms$year_class))) {
  yr  <- levels(fig1c$comp_nb_farms$year_class)[i]
  sbt <- subset(fig1c$comp_nb_farms, year_class == yr)
  points(log10(sbt$nb_farms / 1e6), log10(sbt$estim_nb_farms / 1e6),
         pch = 21, cex = 3, col = "grey20", bg = colr[i])
}
for (cty in c("Angola","Benin","Botswana","Ethiopia","Gabon","Liberia",
              "Malawi","Niger","Nigeria","Rwanda","Sierra Leone")) {
  sbt <- subset(fig1c$comp_nb_farms, country == cty)
  if (nrow(sbt) > 0)
    text(log10(sbt$nb_farms / 1e6), log10(sbt$estim_nb_farms / 1e6) + 0.05,
         labels = sbt$country, col = "grey10", pos = 3, cex = 1.2)
}
legend("bottomright", bty = "n", cex = 1.3,
       title = "Census\ndecade",
       legend = levels(fig1c$comp_nb_farms$year_class),
       pch = 21, pt.cex = 1.7, col = "grey20", pt.bg = colr[1:5])
text(-2.2, 1.35, "C)", cex = 1.5)
text(-0.5,  1.2,  bquote(R^2 == .(round(fig1c$r2_sarah, 2))), cex = 1.5)

# Panel D: OOB density plot
dens <- MASS::kde2d(fig1d_df$x, fig1d_df$y, lims = c(0,3,0,3), n = 500)
image(dens, col = viridis::mako(20, direction = -1)[1:12],
      xlim = c(0,3), ylim = c(0,3),
      xlab = "Reported farm size (ha)", ylab = "Predicted farm size (ha)", main = "",
      cex.axis = 1.2, cex.lab = 1.4, las = 0, mgp = c(2, 0.75, 0))
abline(a = 0, b = 1,   col = "black", lwd = 2)
abline(a = 0, b = 2,   col = "black", lwd = 2, lty = 2)
abline(a = 0, b = 0.5, col = "black", lwd = 2, lty = 2)
text(0.2, 2.75, "D)", cex = 1.5)
text(1.85, 2.65, bquote(R^2 == .(round(0.54, 2))), cex = 1.5)
box()
# Inline density legend
count_matrix <- matrix(
  seq(min(dens$z, na.rm = TRUE), max(dens$z, na.rm = TRUE), length.out = 100), ncol = 1)
rect(2.24, 0, 3, 0.9, border = "black", lwd = 1, col = "white")
image(x = seq(2.25, 2.4, length.out = 2), y = seq(0.05, 0.7, length.out = 100),
      z = t(count_matrix), col = viridis::mako(20, direction = -1)[1:12],
      add = TRUE, xaxt = "n", yaxt = "n")
label_vals <- pretty(range(count_matrix, na.rm = TRUE), n = 5)
label_pos  <- 0.05 + (label_vals - min(count_matrix, na.rm = TRUE)) /
              (max(count_matrix, na.rm = TRUE) - min(count_matrix, na.rm = TRUE)) * (0.7 - 0.05)
for (i in seq_along(label_vals[-length(label_vals)])) {
  segments(2.4, label_pos[i], 2.45, label_pos[i], lwd = 1)
  text(2.46, label_pos[i], format(round(label_vals[i]), scientific = FALSE), adj = 0, cex = 1.2)
}
text(2.25 + (3 - 2.25) / 2, 0.8, "Farms", cex = 1.2)

dev.off()

# ── Report ────────────────────────────────────────────────────────────────────
elapsed <- proc.time()[["elapsed"]] - t0
write_report(
  "F01_main_figure1.R",
  "Main Figure 1: farm density map | farm size map | Lowder nb-farms scatter | OOB density",
  inputs = list(
    "fig.1a raster"  = "../fig.1a_nb_of_farm_per_grid_cell.tif",
    "fig.1c Lowder"  = "../fig.1c_comparison_with_sarah_lowder.rds",
    "fig.1d OOB"     = "../fig.1d_reported_vs_predicted_fsize.rds"
  ),
  outputs = list("Fig.01.png" = "../output/main_fig/Fig.01.png"),
  sections = list(
    "Lowder R2"      = paste("R² =", fig1c$r2_sarah),
    "nb countries"   = paste(nrow(fig1c$comp_nb_farms), "country-census records"),
    "OOB obs"        = paste(nrow(fig1d_df), "farm obs")
  ),
  elapsed_sec = elapsed
)
message("F01 done in ", round(elapsed, 1), "s")
